/**
 * Notification Tables Migration
 *
 * Creates tables for the centralized notification system.
 * Supports in-app notifications, email delivery, and user preferences.
 */
import { db } from './connection.js';

export async function migrateNotifications(): Promise<void> {
  console.log('Running notifications migration...');

  // 1. notifications — every notification generated by the system
  try {
    await db.run(`CREATE TABLE IF NOT EXISTS notifications (
      id VARCHAR(36) PRIMARY KEY,
      recipient_id VARCHAR(36) NOT NULL,
      type ENUM('info','reminder','warning','approval_required','escalation') NOT NULL DEFAULT 'info',
      category VARCHAR(50) NOT NULL COMMENT 'e.g. evaluation, objective, action_plan, vacation, system',
      title VARCHAR(255) NOT NULL,
      body TEXT DEFAULT NULL,
      action_url VARCHAR(500) DEFAULT NULL COMMENT 'Deep link to the relevant resource',
      related_entity_id VARCHAR(36) DEFAULT NULL COMMENT 'ID of the entity that triggered this notification',
      related_entity_type VARCHAR(50) DEFAULT NULL COMMENT 'evaluation, action_plan, etc.',
      is_read TINYINT(1) DEFAULT 0,
      read_at DATETIME DEFAULT NULL,
      is_email_sent TINYINT(1) DEFAULT 0,
      email_sent_at DATETIME DEFAULT NULL,
      is_email_enabled TINYINT(1) DEFAULT 1 COMMENT 'Respects user preference',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      expires_at DATETIME DEFAULT NULL COMMENT 'When this notification becomes stale',
      KEY idx_notif_recipient (recipient_id),
      KEY idx_notif_recipient_read (recipient_id, is_read),
      KEY idx_notif_category (category),
      KEY idx_notif_type (type),
      KEY idx_notif_created (created_at),
      KEY idx_notif_expires (expires_at),
      KEY idx_notif_entity (related_entity_type, related_entity_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
    console.log('  ✓ Created notifications');
  } catch (err: any) {
    if (err.message?.includes('already exists')) console.log('  ✓ notifications already exists');
    else console.error('  ✗ notifications:', err.message?.slice(0, 100));
  }

  // 2. notification_preferences — per-user notification settings
  try {
    await db.run(`CREATE TABLE IF NOT EXISTS notification_preferences (
      id VARCHAR(36) PRIMARY KEY,
      user_id VARCHAR(36) NOT NULL,
      category VARCHAR(50) NOT NULL,
      email_enabled TINYINT(1) DEFAULT 1,
      in_app_enabled TINYINT(1) DEFAULT 1,
      reminder_frequency ENUM('none','daily','3days','weekly') DEFAULT '3days',
      digest_enabled TINYINT(1) DEFAULT 1,
      UNIQUE KEY uq_np_user_category (user_id, category),
      KEY idx_np_user (user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
    console.log('  ✓ Created notification_preferences');
  } catch (err: any) {
    if (err.message?.includes('already exists')) console.log('  ✓ notification_preferences already exists');
    else console.error('  ✗ notification_preferences:', err.message?.slice(0, 100));
  }

  // 3. notification_deliveries — tracks each delivery attempt
  try {
    await db.run(`CREATE TABLE IF NOT EXISTS notification_deliveries (
      id VARCHAR(36) PRIMARY KEY,
      notification_id VARCHAR(36) NOT NULL,
      channel ENUM('in_app','email') NOT NULL,
      status ENUM('pending','sent','failed','bounced') DEFAULT 'pending',
      attempted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      delivered_at DATETIME DEFAULT NULL,
      error_message TEXT DEFAULT NULL,
      KEY idx_nd_notification (notification_id),
      KEY idx_nd_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
    console.log('  ✓ Created notification_deliveries');
  } catch (err: any) {
    if (err.message?.includes('already exists')) console.log('  ✓ notification_deliveries already exists');
    else console.error('  ✗ notification_deliveries:', err.message?.slice(0, 100));
  }

  // 4. Seed default preferences for existing users if table empty
  try {
    const prefCount = await db.get('SELECT COUNT(*) as cnt FROM notification_preferences');
    if ((prefCount as any)?.cnt === 0) {
      const users = await db.all('SELECT id FROM users WHERE is_active = 1');
      const categories = ['evaluation', 'objective', 'action_plan', 'vacation', 'system'];
      for (const u of users as any[]) {
        for (const cat of categories) {
          await db.run(
            `INSERT INTO notification_preferences (id, user_id, category, email_enabled, in_app_enabled, reminder_frequency, digest_enabled) VALUES (?, ?, ?, 1, 1, '3days', 1)`,
            [crypto.randomUUID(), u.id, cat]
          );
        }
      }
      console.log(`  ✓ Seeded preferences for ${users.length} users × ${categories.length} categories`);
    }
  } catch (err: any) {
    console.error('  ✗ Preferences seed error:', err.message?.slice(0, 100));
  }

  console.log('Notifications migration complete.');
}
